name: Setup pnpm (Node via .nvmrc) with cache
description: Enable Corepack, setup pnpm, setup Node from .nvmrc, and configure pnpm store caching

inputs:
  registry-url:
    description: Optional registry URL for authenticated npm/pnpm operations
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Enable Corepack (pnpm)
      shell: bash
      run: corepack enable

    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: .nvmrc
        registry-url: ${{ inputs.registry-url }}

    - name: Get pnpm store path
      id: pnpm-store
      shell: bash
      run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Cache pnpm store
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-
